import { Inter } from "next/font/google";
import "./globals.css";
import { ProfileProvider } from "./component/context/ProfileProvider";
import ToastProvider from "./component/context/ToastProvider";
import { AntdRegistry } from '@ant-design/nextjs-registry';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ProfileProvider>
                    <ToastProvider>
                        <AntdRegistry>
                            {children}
                        </AntdRegistry>
                    </ToastProvider>
                </ProfileProvider>
            </body>
        </html>
    );
}
